# Generated by Django 5.2.7 on 2025-10-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="MOD名")),
                ("content", models.TextField(verbose_name="紹介文")),
                ("link", models.CharField(max_length=150, verbose_name="リンク")),
                (
                    "posted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日時"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mob", "MOB"),
                            ("weapon", "武器"),
                            ("config", "設定"),
                            ("world", "世界"),
                            ("useful", "便利"),
                        ],
                        max_length=50,
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
        ),
    ]
