# Generated by Django 5.2.7 on 2025-10-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koukaapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcontent",
            name="icon",
            field=models.CharField(
                choices=[
                    ("mob-icon", "MOB型"),
                    ("weapon-icon", "武器型"),
                    ("config-icon", "設定型"),
                    ("world-icon", "世界型"),
                    ("useful-icon", "便利型"),
                ],
                default="世界型",
                max_length=50,
                verbose_name="アイコンの種類",
            ),
        ),
    ]
