# Generated by Django 5.2.7 on 2025-11-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koukaapp", "0002_blogcontent_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcontent",
            name="img_key",
            field=models.CharField(default="画像名", verbose_name="挿入画像のキー"),
        ),
    ]
