# Generated by Django 5.2.7 on 2025-11-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("koukaapp", "0003_blogcontent_img_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcontent",
            name="img_key",
            field=models.CharField(
                default="noimage.png", verbose_name="挿入画像のキー"
            ),
        ),
    ]
